#############################################################################
# Makefile for building: predatorPrey
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  predatorPrey.pro
# Template: app
# Command: /home/allen/Qt/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile predatorPrey.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../SFML/include -I../../Qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/allen/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = predatorPrey1.0.0
DISTDIR = /home/allen/Projects/predatorPrey/.tmp/predatorPrey1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lncurses -L/home/allen/SFML/lib -lsfml-graphics-d -lsfml-network-d -lsfml-window-d -lsfml-system-d 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		graphLine/graphline.cpp \
		ecosystem/coordinate/coordinate.cpp \
		ecosystem/ecosystem.cpp \
		ecosystem/creature/creature.cpp \
		ecosystem/creature/predator/predator.cpp \
		ecosystem/creature/prey/prey.cpp \
		ecosystem/creature/wall/wall.cpp 
OBJECTS       = main.o \
		graphline.o \
		coordinate.o \
		ecosystem.o \
		creature.o \
		predator.o \
		prey.o \
		wall.o
DIST          = ../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		predatorPrey.pro graphLine/graphline.h \
		ecosystem/coordinate/coordinate.h \
		ecosystem/ecosystem.h \
		ecosystem/creature/creature.h \
		ecosystem/creature/predator/predator.h \
		ecosystem/creature/prey/prey.h \
		ecosystem/creature/wall/wall.h \
		ecosystem/abstract/moves/moves.h \
		ecosystem/abstract/breeds/breeds.h \
		ecosystem/abstract/eats/eats.h \
		ecosystem/abstract/breeds/breeds.h \
		ecosystem/abstract/eats/eats.h \
		ecosystem/abstract/moves/moves.h \
		ecosystem/abstract/dies/dies.h main.cpp \
		graphLine/graphline.cpp \
		ecosystem/coordinate/coordinate.cpp \
		ecosystem/ecosystem.cpp \
		ecosystem/creature/creature.cpp \
		ecosystem/creature/predator/predator.cpp \
		ecosystem/creature/prey/prey.cpp \
		ecosystem/creature/wall/wall.cpp
QMAKE_TARGET  = predatorPrey
DESTDIR       = 
TARGET        = predatorPrey


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: predatorPrey.pro ../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		predatorPrey.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile predatorPrey.pro
../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.7/gcc_64/mkspecs/features/lex.prf:
predatorPrey.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile predatorPrey.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

graphline.o: graphLine/graphline.cpp graphLine/graphline.h \
		../../SFML/include/SFML/Graphics.hpp \
		../../SFML/include/SFML/Window.hpp \
		../../SFML/include/SFML/System.hpp \
		../../SFML/include/SFML/Config.hpp \
		../../SFML/include/SFML/System/Clock.hpp \
		../../SFML/include/SFML/System/Export.hpp \
		../../SFML/include/SFML/System/Time.hpp \
		../../SFML/include/SFML/System/Err.hpp \
		../../SFML/include/SFML/System/FileInputStream.hpp \
		../../SFML/include/SFML/System/InputStream.hpp \
		../../SFML/include/SFML/System/NonCopyable.hpp \
		../../SFML/include/SFML/System/Lock.hpp \
		../../SFML/include/SFML/System/MemoryInputStream.hpp \
		../../SFML/include/SFML/System/Mutex.hpp \
		../../SFML/include/SFML/System/Sleep.hpp \
		../../SFML/include/SFML/System/String.hpp \
		../../SFML/include/SFML/System/Utf.hpp \
		../../SFML/include/SFML/System/Utf.inl \
		../../SFML/include/SFML/System/String.inl \
		../../SFML/include/SFML/System/Thread.hpp \
		../../SFML/include/SFML/System/Thread.inl \
		../../SFML/include/SFML/System/ThreadLocal.hpp \
		../../SFML/include/SFML/System/ThreadLocalPtr.hpp \
		../../SFML/include/SFML/System/ThreadLocalPtr.inl \
		../../SFML/include/SFML/System/Vector2.hpp \
		../../SFML/include/SFML/System/Vector2.inl \
		../../SFML/include/SFML/System/Vector3.hpp \
		../../SFML/include/SFML/System/Vector3.inl \
		../../SFML/include/SFML/Window/Context.hpp \
		../../SFML/include/SFML/Window/Export.hpp \
		../../SFML/include/SFML/Window/GlResource.hpp \
		../../SFML/include/SFML/Window/ContextSettings.hpp \
		../../SFML/include/SFML/Window/Event.hpp \
		../../SFML/include/SFML/Window/Joystick.hpp \
		../../SFML/include/SFML/Window/Keyboard.hpp \
		../../SFML/include/SFML/Window/Mouse.hpp \
		../../SFML/include/SFML/Window/Sensor.hpp \
		../../SFML/include/SFML/Window/Touch.hpp \
		../../SFML/include/SFML/Window/VideoMode.hpp \
		../../SFML/include/SFML/Window/Window.hpp \
		../../SFML/include/SFML/Window/WindowHandle.hpp \
		../../SFML/include/SFML/Window/WindowStyle.hpp \
		../../SFML/include/SFML/Graphics/BlendMode.hpp \
		../../SFML/include/SFML/Graphics/Export.hpp \
		../../SFML/include/SFML/Graphics/CircleShape.hpp \
		../../SFML/include/SFML/Graphics/Shape.hpp \
		../../SFML/include/SFML/Graphics/Drawable.hpp \
		../../SFML/include/SFML/Graphics/RenderStates.hpp \
		../../SFML/include/SFML/Graphics/Transform.hpp \
		../../SFML/include/SFML/Graphics/Rect.hpp \
		../../SFML/include/SFML/Graphics/Rect.inl \
		../../SFML/include/SFML/Graphics/Transformable.hpp \
		../../SFML/include/SFML/Graphics/VertexArray.hpp \
		../../SFML/include/SFML/Graphics/Vertex.hpp \
		../../SFML/include/SFML/Graphics/Color.hpp \
		../../SFML/include/SFML/Graphics/PrimitiveType.hpp \
		../../SFML/include/SFML/Graphics/ConvexShape.hpp \
		../../SFML/include/SFML/Graphics/Font.hpp \
		../../SFML/include/SFML/Graphics/Glyph.hpp \
		../../SFML/include/SFML/Graphics/Texture.hpp \
		../../SFML/include/SFML/Graphics/Image.hpp \
		../../SFML/include/SFML/Graphics/RectangleShape.hpp \
		../../SFML/include/SFML/Graphics/RenderTarget.hpp \
		../../SFML/include/SFML/Graphics/View.hpp \
		../../SFML/include/SFML/Graphics/RenderTexture.hpp \
		../../SFML/include/SFML/Graphics/RenderWindow.hpp \
		../../SFML/include/SFML/Graphics/Shader.hpp \
		../../SFML/include/SFML/Graphics/Glsl.hpp \
		../../SFML/include/SFML/Graphics/Glsl.inl \
		../../SFML/include/SFML/Graphics/Sprite.hpp \
		../../SFML/include/SFML/Graphics/Text.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphline.o graphLine/graphline.cpp

coordinate.o: ecosystem/coordinate/coordinate.cpp ecosystem/coordinate/coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coordinate.o ecosystem/coordinate/coordinate.cpp

ecosystem.o: ecosystem/ecosystem.cpp ecosystem/ecosystem.h \
		graphLine/graphline.h \
		../../SFML/include/SFML/Graphics.hpp \
		../../SFML/include/SFML/Window.hpp \
		../../SFML/include/SFML/System.hpp \
		../../SFML/include/SFML/Config.hpp \
		../../SFML/include/SFML/System/Clock.hpp \
		../../SFML/include/SFML/System/Export.hpp \
		../../SFML/include/SFML/System/Time.hpp \
		../../SFML/include/SFML/System/Err.hpp \
		../../SFML/include/SFML/System/FileInputStream.hpp \
		../../SFML/include/SFML/System/InputStream.hpp \
		../../SFML/include/SFML/System/NonCopyable.hpp \
		../../SFML/include/SFML/System/Lock.hpp \
		../../SFML/include/SFML/System/MemoryInputStream.hpp \
		../../SFML/include/SFML/System/Mutex.hpp \
		../../SFML/include/SFML/System/Sleep.hpp \
		../../SFML/include/SFML/System/String.hpp \
		../../SFML/include/SFML/System/Utf.hpp \
		../../SFML/include/SFML/System/Utf.inl \
		../../SFML/include/SFML/System/String.inl \
		../../SFML/include/SFML/System/Thread.hpp \
		../../SFML/include/SFML/System/Thread.inl \
		../../SFML/include/SFML/System/ThreadLocal.hpp \
		../../SFML/include/SFML/System/ThreadLocalPtr.hpp \
		../../SFML/include/SFML/System/ThreadLocalPtr.inl \
		../../SFML/include/SFML/System/Vector2.hpp \
		../../SFML/include/SFML/System/Vector2.inl \
		../../SFML/include/SFML/System/Vector3.hpp \
		../../SFML/include/SFML/System/Vector3.inl \
		../../SFML/include/SFML/Window/Context.hpp \
		../../SFML/include/SFML/Window/Export.hpp \
		../../SFML/include/SFML/Window/GlResource.hpp \
		../../SFML/include/SFML/Window/ContextSettings.hpp \
		../../SFML/include/SFML/Window/Event.hpp \
		../../SFML/include/SFML/Window/Joystick.hpp \
		../../SFML/include/SFML/Window/Keyboard.hpp \
		../../SFML/include/SFML/Window/Mouse.hpp \
		../../SFML/include/SFML/Window/Sensor.hpp \
		../../SFML/include/SFML/Window/Touch.hpp \
		../../SFML/include/SFML/Window/VideoMode.hpp \
		../../SFML/include/SFML/Window/Window.hpp \
		../../SFML/include/SFML/Window/WindowHandle.hpp \
		../../SFML/include/SFML/Window/WindowStyle.hpp \
		../../SFML/include/SFML/Graphics/BlendMode.hpp \
		../../SFML/include/SFML/Graphics/Export.hpp \
		../../SFML/include/SFML/Graphics/CircleShape.hpp \
		../../SFML/include/SFML/Graphics/Shape.hpp \
		../../SFML/include/SFML/Graphics/Drawable.hpp \
		../../SFML/include/SFML/Graphics/RenderStates.hpp \
		../../SFML/include/SFML/Graphics/Transform.hpp \
		../../SFML/include/SFML/Graphics/Rect.hpp \
		../../SFML/include/SFML/Graphics/Rect.inl \
		../../SFML/include/SFML/Graphics/Transformable.hpp \
		../../SFML/include/SFML/Graphics/VertexArray.hpp \
		../../SFML/include/SFML/Graphics/Vertex.hpp \
		../../SFML/include/SFML/Graphics/Color.hpp \
		../../SFML/include/SFML/Graphics/PrimitiveType.hpp \
		../../SFML/include/SFML/Graphics/ConvexShape.hpp \
		../../SFML/include/SFML/Graphics/Font.hpp \
		../../SFML/include/SFML/Graphics/Glyph.hpp \
		../../SFML/include/SFML/Graphics/Texture.hpp \
		../../SFML/include/SFML/Graphics/Image.hpp \
		../../SFML/include/SFML/Graphics/RectangleShape.hpp \
		../../SFML/include/SFML/Graphics/RenderTarget.hpp \
		../../SFML/include/SFML/Graphics/View.hpp \
		../../SFML/include/SFML/Graphics/RenderTexture.hpp \
		../../SFML/include/SFML/Graphics/RenderWindow.hpp \
		../../SFML/include/SFML/Graphics/Shader.hpp \
		../../SFML/include/SFML/Graphics/Glsl.hpp \
		../../SFML/include/SFML/Graphics/Glsl.inl \
		../../SFML/include/SFML/Graphics/Sprite.hpp \
		../../SFML/include/SFML/Graphics/Text.hpp \
		ecosystem/creature/creature.h \
		ecosystem/coordinate/coordinate.h \
		ecosystem/creature/predator/predator.h \
		ecosystem/abstract/moves/moves.h \
		ecosystem/abstract/breeds/breeds.h \
		ecosystem/abstract/dies/dies.h \
		ecosystem/abstract/eats/eats.h \
		ecosystem/creature/prey/prey.h \
		ecosystem/creature/wall/wall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ecosystem.o ecosystem/ecosystem.cpp

creature.o: ecosystem/creature/creature.cpp ecosystem/creature/creature.h \
		ecosystem/coordinate/coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creature.o ecosystem/creature/creature.cpp

predator.o: ecosystem/creature/predator/predator.cpp ecosystem/creature/predator/predator.h \
		ecosystem/creature/creature.h \
		ecosystem/coordinate/coordinate.h \
		ecosystem/abstract/moves/moves.h \
		ecosystem/abstract/breeds/breeds.h \
		ecosystem/abstract/dies/dies.h \
		ecosystem/abstract/eats/eats.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o predator.o ecosystem/creature/predator/predator.cpp

prey.o: ecosystem/creature/prey/prey.cpp ecosystem/creature/prey/prey.h \
		ecosystem/creature/creature.h \
		ecosystem/coordinate/coordinate.h \
		ecosystem/abstract/moves/moves.h \
		ecosystem/abstract/breeds/breeds.h \
		ecosystem/abstract/dies/dies.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prey.o ecosystem/creature/prey/prey.cpp

wall.o: ecosystem/creature/wall/wall.cpp ecosystem/creature/wall/wall.h \
		ecosystem/creature/creature.h \
		ecosystem/coordinate/coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wall.o ecosystem/creature/wall/wall.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

